services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  backend:
    image: nathan2830/backend:latest

    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

      JWT_SECRET: ${JWT_SECRET}
      APP_BASE_URL: ${APP_BASE_URL}

      ALIYUN_OSS_ENDPOINT: ${ALIYUN_OSS_ENDPOINT}
      ALIYUN_OSS_BUCKET: ${ALIYUN_OSS_BUCKET}
      ALIYUN_OSS_ACCESS_KEY_ID: ${ALIYUN_OSS_ACCESS_KEY_ID}
      ALIYUN_OSS_ACCESS_KEY_SECRET: ${ALIYUN_OSS_ACCESS_KEY_SECRET}
      ALIYUN_OSS_BASE_URL: ${ALIYUN_OSS_BASE_URL}

    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    image: nathan2830/frontend:latest
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  db_data: